TOPICS = {
    "art history",
    "marine conservation",
    "aviation history",
    "mythical creatures",
    "dairy farming",
    "humanitarian aid",
    "environmental science",
    "gardening tools",
    "world music",
    "waste reduction",
    "reptiles",
    "sustainable agriculture",
    "endangered species",
    "asian culture",
    "biodiversity",
    "organic farming",
    "canine behavior",
    "latin american culture",
    "traditional crafts",
    "primatology",
    "human rights",
    "brewing history",
    "capital punishment",
    "natural disasters",
    "pedagogy",
    "pottery",
    "glass art",
    "monarchies",
    "wildlife",
    "burial practices",
    "card games",
    "mindfulness",
    "green living",
    "historic inventions",
    "ocean life",
    "botanical science",
    "performing arts",
    "gourmet cooking",
    "wild canines",
    "material science",
    "playground equipment",
    "societal issues",
    "orchestral music",
    "ornithology",
    "ancient myths",
    "fiber arts",
    "soccer",
    "logic puzzles",
    "comparative religion",
    "macroeconomics",
    "ancient cultures",
    "hammock making",
    "cotton production",
    "cartography",
    "urban development",
    "gemology",
    "cultural studies",
    "european history",
    "bohemian lifestyle",
    "civil engineering",
    "spa culture",
    "digital communications",
    "mineral extraction",
    "woodworking",
    "broadcast media",
    "human anatomy",
    "equine science",
    "mathematical theory",
    "international sports",
    "board games",
    "world history",
    "computational theory",
    "lighthouse engineering",
    "carpentry",
    "match manufacturing",
    "athletic training",
    "airport logistics",
    "clown performance",
    "beach volleyball",
    "spelunking",
    "ceramic arts",
    "swine farming",
    "quantum mechanics",
    "immunology",
    "automotive technology",
    "professional wrestling",
    "romani culture",
    "recycling systems",
    "fossil fuel impact",
    "joinery",
    "dietary science",
    "large mammals",
    "automation",
    "salt mining",
    "language studies",
    "railway systems",
    "fashion design",
    "earth sciences",
    "poetic forms",
    "sheep herding",
    "children's playgrounds",
    "barbering",
    "internet security",
    "mule breeding",
    "baking",
    "currency systems",
    "stone masonry",
    "gaming culture",
    "entomology",
    "penology",
    "comic book art",
    "magic tricks",
    "nautical vessels",
    "wind energy",
    "organ music",
    "bicycle sports",
    "surf culture",
    "circus arts",
    "environmental protection",
    "plant sciences",
    "sugar production",
    "rail transport",
    "mass media",
    "shoe repair",
    "wildlife conservation",
    "gorilla behavior",
    "local food markets",
    "competitive sports",
    "theatrical performance",
    "rhinoceros conservation",
    "seismology",
    "tropical fruits",
    "shark biology",
    "firefighting",
    "craft brewing",
    "cinematography",
    "pharmaceuticals",
    "amphibians",
    "maternal health",
    "apiology",
    "wildlife preservation",
    "animation techniques",
    "coffee culture",
    "fine arts",
    "textile arts",
    "skydiving",
    "collectible cards",
    "digital photography",
    "documentary production",
    "astronautics",
    "canoeing",
    "fencing",
    "puppet theater",
    "reptilian species",
    "ice hockey",
    "ballet dancing",
    "legal studies",
    "modern technology",
    "root vegetables",
    "volcanology",
    "tobacco industry",
    "weather forecasting",
    "banana cultivation",
    "psychological studies",
    "mechanical engineering",
    "creative inventions",
    "rugby",
    "wildlife biology",
    "musical instruments",
    "airship history",
    "parachuting",
    "tobacco products",
    "acrobatics",
    "medical imaging",
    "textile manufacturing",
    "electronic sports",
    "cricket",
    "ignition devices",
    "leather crafting",
    "journalism",
    "vanilla farming",
    "cue sports",
    "maritime history",
    "golf",
    "leisure activities",
    "marine ecosystems",
    "social sciences",
    "medical practices",
    "cheese making",
    "fortune telling",
    "buddhist studies",
    "martial arts",
    "amphibian species",
    "news delivery",
    "disease research",
    "pack animals",
    "bread making",
    "printing technology",
    "weaving",
    "dental care",
    "boxing",
    "indigenous cultures",
    "aviation",
    "sailing",
    "fashion history",
    "caprine animals",
    "bison",
    "primates",
    "hunting practices",
    "hospitality",
    "chiropterology",
    "bakery operations",
    "nuclear power",
    "association football",
    "mountaineering",
    "transport logistics",
    "news reporting",
    "philosophy",
    "motorcycling",
    "communication devices",
    "military history",
    "criminal behavior",
    "legal systems",
    "basketball",
    "archery",
    "criminology",
    "ferry transportation",
    "literature",
    "funerary customs",
    "pharmacy operations",
    "political science",
    "desert environments",
    "public transit",
    "crime prevention",
    "brewing science",
    "leatherworking",
    "pharmacology",
    "mountain climbing",
    "political ideologies",
    "mummification",
    "stadium design",
    "financial systems",
    "armed forces",
    "big cats",
    "water management",
    "mortality",
    "hot air balloons",
    "mountain ranges",
    "world war i",
    "leather tanning",
    "chess strategy",
    "culinary techniques",
    "pork production",
    "occupational studies",
    "architectural design",
    "literacy",
    "dance styles",
    "cinema history",
    "insect study",
    "yoga practice",
    "carousel design",
    "comedy performance",
    "scouting",
    "angling",
    "medical research",
    "forest ecology",
    "elephant behavior",
    "plant biology",
    "historical figures",
    "reptile studies",
    "documentary filmmaking",
    "coal mining",
    "natural events",
    "scientific research",
    "baseball",
    "metalwork",
    "aerospace engineering",
    "cycling",
    "distillation",
    "jazz music",
    "african cultures",
    "smoking cessation",
    "seashells",
    "horticulture",
    "community service",
    "numismatics",
    "smoking pipes",
    "veterinary science",
    "astronomy",
    "radio broadcasting",
    "river ecosystems",
    "rice cultivation",
    "funerary practices",
    "camel breeding",
    "accordion music",
    "climate science",
    "gold mining",
    "marine archaeology",
    "zoology",
    "building construction",
    "renewable energy",
    "blockchain",
    "cryptocurrency",
    "bitcoin",
    "professional e-sports",
    "professional cricket",
    "youe favorite bars in the area",
    "your favorite workout routine",
    "your favorite restaurant in the area",
}